# Numpy All 

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array([(1,2,3,4,56), (5,8,6,9,7)])

array([[ 1,  2,  3,  4, 56],
       [ 5,  8,  6,  9,  7]])

In [5]:
## Creating an array from a list

num_list = [1,2,3,4,5]

np.array(num_list)

array([1, 2, 3, 4, 5])

# Genereting Array 

NumPy offers various options to generate an array depending on particular need, such as:

~Generating identity array
~Generating zero array of a given size
~Generating ones array with a given size
~Generating an array in a given range
~Generating an array with random values

In [6]:
#generating the matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# You can multiply with any constant
np.eye(4)*7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [8]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
## Generating an array in a given range or interval

np.arange(0,5)

array([0, 1, 2, 3, 4])

In [10]:
#creating one  array of a give size
#1- dimensional one 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
#creating two dimesion ones array pass in the tuple of rows and colums number.
#np.ones((row,columms))
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#generating an array in a given range or interval
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
#if you want to conrol the step size
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#you can also use linespace to generate an evenly spaced number in a given interval
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
##Generating an array with random values
## Create a 1D array with 4 random number 
np.random.rand(4)

array([0.06580775, 0.22836353, 0.21797367, 0.74043696])

In [16]:
np.random.rand(4,5)

array([[0.47097815, 0.96529695, 0.21726496, 0.55242508, 0.42118256],
       [0.56426331, 0.13767816, 0.08432216, 0.47179687, 0.03560026],
       [0.88906248, 0.09542988, 0.33844217, 0.146828  , 0.41386644],
       [0.93599854, 0.46456817, 0.30355082, 0.79954361, 0.15178571]])

In [17]:
#Generating one random integer r in a given range 
np.random.randint(4,50)

44

In [18]:
#Generating 10 random interger in given range 
np.random.randint(1,50,10)

array([28, 19, 33,  3, 11, 35, 49, 38, 46,  6])

In [19]:
##Random see to output the same random value at all run time 
#The seed() method is used to initialize the random number generator.
#The random number generator needs a number to start with (a seed value), to be able to generate a random number.
import random
random.seed(10)
random.randint(5,50)

41

# 2.Data Selection:Indexing  and slicing an array 

In [20]:
#Creating a 1 dimensional vector
array_1d =np.array([1,2,3,4,5,6])
#slicing:Returning the group of element from an array 
array_1d[5]


6

In [21]:
array_1d[-2]

5

In [22]:
#slicing :returning group of element from an array
array_1d[2:4]


array([3, 4])

In [23]:
##indexing 2D Array 
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
array_2d[1][2]

6

In [26]:
# return the last two column
array_2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

# condition selection 

In [29]:
arr=np.array(([1,2,3],[3,4,5],[7,8,9]))

In [35]:
## select all the element in array which is  less than 4
array[arr<4]


array([1, 2, 3, 3])

In [36]:
array[arr>6]

array([7, 8, 9])

In [40]:
#select the even number 
array[arr%2==0]

array([2, 4, 8])

In [41]:
# select the odd number in array 
array[arr%2!=0]

array([1, 3, 3, 5, 7, 9])

In [44]:
#multiple condition
# In all odd number ,return value which are greater or equal to 5
arr[(arr%2!=0)&(arr>=5)]

array([5, 7, 9])

In [45]:
arr>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [49]:
arr==1

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

# 3) BASIC ARRAY operations

In [51]:
#create two array 
arr1=np.arange(0,5)
arr2=np.arange(6,11)

In [55]:
##addition 
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [56]:
#subtration 
arr1-arr2

array([-6, -6, -6, -6, -6])

In [57]:
#multiplication
arr1*arr2

array([ 0,  7, 16, 27, 40])

In [58]:
##DIVISION
arr1/arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [60]:
#sqaring
arr1**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [62]:
#calculating the sum of two number 
np.add(arr1,arr2)

array([ 6,  8, 10, 12, 14])

In [64]:
np.subtract(arr1,arr2)

array([-6, -6, -6, -6, -6])

In [65]:
np.divide(arr1,arr2)

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [66]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [68]:
np.sin([0,45,90,180])

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264])

In [69]:
np.log(arr2)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [70]:
#calculating the exponent(ex or e^)of the array 
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [71]:
np.power(arr1,arr2)

array([      0,       1,     256,   19683, 1048576], dtype=int32)

# Basic Statistics

In [72]:
#creating an array 
arr =np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

# Standard Deviation 

In [73]:
np.std(arr)

1.4142135623730951